import { NotificationList } from "@/components/app/NotificationList";
import { PageHeader } from "@/components/app/PageHeader";
import { EmptyState } from "@/components/ui/EmptyState";
import { requireAuthOrRedirect } from "@/lib/auth/guards";
import { repository } from "@/lib/data/repository";

export default async function NotificationsPage() {
  const user = await requireAuthOrRedirect("/dashboard/notifications");
  const notifications = await repository.listNotifications(user.id);

  return (
    <div className="space-y-6">
      <PageHeader
        title="Notifications"
        description="Updates generated by the platform when your inquiries, orders, or payments change."
      />

      {notifications.length === 0 ? (
        <EmptyState
          title="Nothing to read"
          description="Platform updates about your inquiries, orders, and payments will show up here."
        />
      ) : (
        <NotificationList notifications={notifications} />
      )}
    </div>
  );
}
